/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in (OAuth2 form)
         * @description Standard OAuth2 password flow. `username` carries the email address.
         *
         *     This is the endpoint Swagger's Authorize button uses.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in (JSON)
         * @description JSON login, used by the React client.
         */
        post: operations["login_json_api_v1_auth_login_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description The caller, with the permissions their role holds.
         *
         *     The frontend uses the permission list to hide controls. It is a usability
         *     affordance, not a security boundary - every endpoint checks independently.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Used to populate investigator-assignment dropdowns.
         */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        /**
         * Create user
         * @description Admin-only. Emails are normalised to lowercase so login is case-insensitive.
         */
        post: operations["create_user_api_v1_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All domain enums
         * @description Single source of dropdown options for the entire frontend.
         */
        get: operations["get_vocabulary_api_v1_meta_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Unauthenticated liveness check used by Docker, CI and the smoke tests.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /**
         * EnumOption
         * @description A selectable option. `label` is display text derived from the value.
         */
        EnumOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description JSON login, alongside the OAuth2 form endpoint.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Token
         * @description OAuth2 bearer token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Expires In Minutes */
            expires_in_minutes: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserCreate
         * @description Admin-only user creation.
         */
        UserCreate: {
            /** Department */
            department?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** @default viewer */
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRead
         * @description A user as returned by the API. Never includes the password hash.
         */
        UserRead: {
            /** Department */
            department?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @description Access roles. Ordering here is not privilege ordering - see core.rbac.
         * @enum {string}
         */
        UserRole: "admin" | "qa_manager" | "complaint_officer" | "investigator" | "viewer";
        /**
         * UserWithPermissions
         * @description `/auth/me` response.
         *
         *     Permissions are sent so the UI can hide controls the user cannot use. This is
         *     presentation only - every endpoint enforces independently, and a tampered
         *     client gains nothing.
         */
        UserWithPermissions: {
            /** Department */
            department?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Permissions */
            permissions?: string[];
            role: components["schemas"]["UserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VocabularyResponse
         * @description Every enum the intake form and filters need, in one round trip.
         */
        VocabularyResponse: {
            /** Complaint Sources */
            complaint_sources: components["schemas"]["EnumOption"][];
            /** Complaint Statuses */
            complaint_statuses: components["schemas"]["EnumOption"][];
            /** Complaint Types */
            complaint_types: components["schemas"]["EnumOption"][];
            /** Document Kinds */
            document_kinds: components["schemas"]["EnumOption"][];
            /** Dosage Forms */
            dosage_forms: components["schemas"]["EnumOption"][];
            /** Priorities */
            priorities: components["schemas"]["EnumOption"][];
            /** Quantity Units */
            quantity_units: components["schemas"]["EnumOption"][];
            /** Severities */
            severities: components["schemas"]["EnumOption"][];
            /** User Roles */
            user_roles: components["schemas"]["EnumOption"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_json_api_v1_auth_login_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithPermissions"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    create_user_api_v1_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocabulary_api_v1_meta_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
