/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All domain enums
         * @description Single source of dropdown options for the entire frontend.
         */
        get: operations["get_vocabulary_api_v1_meta_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Unauthenticated liveness check used by Docker, CI and the smoke tests.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EnumOption
         * @description A selectable option. `label` is display text derived from the value.
         */
        EnumOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * VocabularyResponse
         * @description Every enum the intake form and filters need, in one round trip.
         */
        VocabularyResponse: {
            /** Complaint Sources */
            complaint_sources: components["schemas"]["EnumOption"][];
            /** Complaint Statuses */
            complaint_statuses: components["schemas"]["EnumOption"][];
            /** Complaint Types */
            complaint_types: components["schemas"]["EnumOption"][];
            /** Document Kinds */
            document_kinds: components["schemas"]["EnumOption"][];
            /** Dosage Forms */
            dosage_forms: components["schemas"]["EnumOption"][];
            /** Priorities */
            priorities: components["schemas"]["EnumOption"][];
            /** Quantity Units */
            quantity_units: components["schemas"]["EnumOption"][];
            /** Severities */
            severities: components["schemas"]["EnumOption"][];
            /** User Roles */
            user_roles: components["schemas"]["EnumOption"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_vocabulary_api_v1_meta_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
