"""initial schema: users, reference data, complaints, investigation, audit

Revision ID: 96f2c04b1038
Revises: 
Create Date: 2026-09-11 12:51:04.696819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f2c04b1038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.Enum('EMAIL', 'PHONE', 'CUSTOMER_PORTAL', 'SALES_REPRESENTATIVE', 'DISTRIBUTOR', 'HOSPITAL_PHARMACY', 'RETAIL_PHARMACY', 'REGULATORY_AUTHORITY', 'FIELD_ALERT', 'WRITTEN_LETTER', 'OTHER', name='customer_type', native_enum=False, length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.Enum('TABLET', 'CAPSULE', 'INJECTION', 'SYRUP', 'SUSPENSION', 'CREAM', 'OINTMENT', 'GEL', 'DROPS', 'INHALER', 'POWDER', 'SACHET', 'SUPPOSITORY', 'PATCH', 'OTHER', name='dosage_form', native_enum=False, length=40), nullable=True),
    sa.Column('product_code', sa.String(length=60), nullable=True),
    sa.Column('therapeutic_category', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'QA_MANAGER', 'COMPLAINT_OFFICER', 'INVESTIGATOR', 'VIEWER', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'STATUS_CHANGED', 'DELETED', 'DOCUMENT_UPLOADED', 'AI_EXTRACTION', 'AI_ASSESSMENT', 'ASSIGNED', 'LOGIN', name='audit_action', native_enum=False, length=40), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_entries_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entries'))
    )
    op.create_index(op.f('ix_audit_entries_actor_id'), 'audit_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_entity_id'), 'audit_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_entity_type'), 'audit_entries', ['entity_type'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_produced', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('quantity_unit', sa.Enum('TABLETS', 'CAPSULES', 'VIALS', 'AMPOULES', 'BOTTLES', 'BLISTERS', 'SACHETS', 'TUBES', 'BOXES', 'CARTONS', 'UNITS', 'KG', 'G', 'MG', 'L', 'ML', name='quantity_unit', native_enum=False, length=30), nullable=True),
    sa.Column('manufacturing_site', sa.String(length=160), nullable=True),
    sa.Column('units_released', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_batches_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('product_id', 'batch_number', name='product_batch')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=30), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'PHONE', 'CUSTOMER_PORTAL', 'SALES_REPRESENTATIVE', 'DISTRIBUTOR', 'HOSPITAL_PHARMACY', 'RETAIL_PHARMACY', 'REGULATORY_AUTHORITY', 'FIELD_ALERT', 'WRITTEN_LETTER', 'OTHER', name='complaint_source', native_enum=False, length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('reporter_name', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.Enum('TABLET', 'CAPSULE', 'INJECTION', 'SYRUP', 'SUSPENSION', 'CREAM', 'OINTMENT', 'GEL', 'DROPS', 'INHALER', 'POWDER', 'SACHET', 'SUPPOSITORY', 'PATCH', 'OTHER', name='cmp_dosage_form', native_enum=False, length=40), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_affected', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_unit', sa.Enum('TABLETS', 'CAPSULES', 'VIALS', 'AMPOULES', 'BOTTLES', 'BLISTERS', 'SACHETS', 'TUBES', 'BOXES', 'CARTONS', 'UNITS', 'KG', 'G', 'MG', 'L', 'ML', name='cmp_quantity_unit', native_enum=False, length=30), nullable=True),
    sa.Column('complaint_type', sa.Enum('APPEARANCE_DISCOLORATION', 'FOREIGN_MATTER', 'CONTAMINATION_MICROBIAL', 'CONTAMINATION_CROSS', 'PACKAGING_DEFECT', 'LABELING_ERROR', 'PHYSICAL_DAMAGE', 'BROKEN_OR_CHIPPED', 'ODOR_OR_TASTE', 'DISSOLUTION_FAILURE', 'ASSAY_OUT_OF_SPECIFICATION', 'STABILITY_DEFECT', 'EFFICACY_COMPLAINT', 'ADVERSE_EVENT', 'SHORT_COUNT_OR_FILL', 'TAMPER_EVIDENCE', 'DEVICE_MALFUNCTION', 'OTHER', name='complaint_type', native_enum=False, length=50), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severity', native_enum=False, length=20), nullable=True),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='priority', native_enum=False, length=20), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'INVESTIGATION', 'ROOT_CAUSE_IDENTIFIED', 'CAPA_REQUIRED', 'QA_REVIEW', 'CLOSED', name='complaint_status', native_enum=False, length=40), nullable=False),
    sa.Column('assigned_investigator_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.id'], name=op.f('fk_complaints_assigned_investigator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_complaints_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_complaints_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_complaints_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_complaints_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_assigned_investigator_id'), 'complaints', ['assigned_investigator_id'], unique=False)
    op.create_index(op.f('ix_complaints_batch_id'), 'complaints', ['batch_id'], unique=False)
    op.create_index(op.f('ix_complaints_batch_number'), 'complaints', ['batch_number'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_date'), 'complaints', ['complaint_date'], unique=False)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_customer_name'), 'complaints', ['customer_name'], unique=False)
    op.create_index(op.f('ix_complaints_due_date'), 'complaints', ['due_date'], unique=False)
    op.create_index(op.f('ix_complaints_product_id'), 'complaints', ['product_id'], unique=False)
    op.create_index(op.f('ix_complaints_product_name'), 'complaints', ['product_name'], unique=False)
    op.create_index(op.f('ix_complaints_reference_code'), 'complaints', ['reference_code'], unique=True)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('ai_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_ai_assessments_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_assessments'))
    )
    op.create_index(op.f('ix_ai_assessments_complaint_id'), 'ai_assessments', ['complaint_id'], unique=False)
    op.create_table('capas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effectiveness_check', sa.Text(), nullable=True),
    sa.Column('effectiveness_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_capas_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_capas_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capas'))
    )
    op.create_index(op.f('ix_capas_complaint_id'), 'capas', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_capas_due_date'), 'capas', ['due_date'], unique=False)
    op.create_index(op.f('ix_capas_owner_id'), 'capas', ['owner_id'], unique=False)
    op.create_table('complaint_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('PDF', 'DOCX', 'TXT', 'EML', 'PNG', 'JPG', name='document_kind', native_enum=False, length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_documents_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_complaint_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_documents'))
    )
    op.create_index(op.f('ix_complaint_documents_complaint_id'), 'complaint_documents', ['complaint_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('methodology', sa.String(length=200), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('samples_examined', sa.Text(), nullable=True),
    sa.Column('batch_record_review', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_investigations_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], name=op.f('fk_investigations_investigator_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_complaint_id'), 'investigations', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigator_id'), 'investigations', ['investigator_id'], unique=False)
    op.create_table('root_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_root_causes_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_root_causes_confirmed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_root_causes'))
    )
    op.create_index(op.f('ix_root_causes_complaint_id'), 'root_causes', ['complaint_id'], unique=False)
    op.create_table('status_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'UNDER_REVIEW', 'INVESTIGATION', 'ROOT_CAUSE_IDENTIFIED', 'CAPA_REQUIRED', 'QA_REVIEW', 'CLOSED', name='from_status', native_enum=False, length=40), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'UNDER_REVIEW', 'INVESTIGATION', 'ROOT_CAUSE_IDENTIFIED', 'CAPA_REQUIRED', 'QA_REVIEW', 'CLOSED', name='to_status', native_enum=False, length=40), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_status_transitions_changed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_status_transitions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_transitions'))
    )
    op.create_index(op.f('ix_status_transitions_complaint_id'), 'status_transitions', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_transitions_complaint_id'), table_name='status_transitions')
    op.drop_table('status_transitions')
    op.drop_index(op.f('ix_root_causes_complaint_id'), table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_investigations_investigator_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_complaint_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_complaint_documents_complaint_id'), table_name='complaint_documents')
    op.drop_table('complaint_documents')
    op.drop_index(op.f('ix_capas_owner_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_due_date'), table_name='capas')
    op.drop_index(op.f('ix_capas_complaint_id'), table_name='capas')
    op.drop_table('capas')
    op.drop_index(op.f('ix_ai_assessments_complaint_id'), table_name='ai_assessments')
    op.drop_table('ai_assessments')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reference_code'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_product_name'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_product_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_due_date'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_name'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_date'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_batch_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_batch_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_investigator_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_entries_entity_type'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_entity_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
